name: Audit

on: pull_request

jobs:
  build:
    name: Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: luisfontes19/npm-audit-action@v0.1.0
        with:
          fix: true
          github-token: ${{ secrets.GH_TOKEN }}
